image:
  name: logdna/logdna-agent
  tag: 1.5.6
  pullPolicy: IfNotPresent

logdna:
  ## Please follow directions from https://app.logdna.com/pages/add-source

  ## An ingestion key or custom secrets template is required to run this chart
  key: ""
  ## secrets: ""

  ## Optional settings
  autoupdate: "0"
  tags: ""
  apihost: api.logdna.com
  loghost: logs.logdna.com
  name: logdna-agent

resources:
  requests:
    cpu: 20m
  limits:
    memory: 500Mi

daemonset:
  # updateStrategy:
  #   type: "RollingUpdate"
  tolerations: []

priorityClassName: ""

# updateOnSecretChange: true
